name: Modify and release

on:
  workflow_dispatch:

jobs:
  modify_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out upstream repo
        uses: actions/checkout@v3
        with:
          repository: TeamNewPipe/NewPipe

      - name: Modify code
        run: |
          filepath="app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadManager.kt"

          orig_line_1="private const val PARALLEL_EXTRACTIONS = 3"
          new_line_1="private const val PARALLEL_EXTRACTIONS = 6"

          orig_line_2="private const val BATCH_SIZE = 50"
          new_line_2="private const val BATCH_SIZE = 9999"

          sed -i "s|$orig_line_1|$new_line_1|" $filepath
          sed -i "s|$orig_line_2|$new_line_2|" $filepath
    
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: "Build release APK"
        run: ./gradlew assembledebug --stacktrace

      - name: "Rename APK"
        run: |
          VERSION_NAME="$(jq -r ".elements[0].versionName" "app/build/outputs/apk/release/output-metadata.json")"
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "Version name: $VERSION_NAME" >> "$GITHUB_STEP_SUMMARY"
          echo '```json' >> "$GITHUB_STEP_SUMMARY"
          cat "app/build/outputs/apk/release/output-metadata.json" >> "$GITHUB_STEP_SUMMARY"
          echo >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          # assume there is only one APK in that folder
          mv app/build/outputs/apk/release/*.apk "app/build/outputs/apk/release/NewPipe_v$VERSION_NAME.apk"
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.VERSION_NAME }}
          release_name: v${{ env.VERSION_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Upload APK to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/NewPipe_v${{ env.VERSION_NAME }}.apk
          asset_name: NewPipe_v${{ env.VERSION_NAME }}_perf.apk
          asset_content_type: application/vnd.android.package-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
