name: Modify and release

on:
  workflow_dispatch:

jobs:
  modify_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Install zipalign
        run: |
          sudo apt update
          sudo apt install android-sdk-build-tools
        
      - name: Check out upstream repo
        uses: actions/checkout@v3
        with:
          repository: TeamNewPipe/NewPipe

      - name: Modify code
        run: |
          filepath="app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadManager.kt"

          orig_line_1="private const val PARALLEL_EXTRACTIONS = 3"
          new_line_1="private const val PARALLEL_EXTRACTIONS = 6"

          orig_line_2="private const val BATCH_SIZE = 50"
          new_line_2="private const val BATCH_SIZE = 9999"

          sed -i "s|$orig_line_1|$new_line_1|" $filepath
          sed -i "s|$orig_line_2|$new_line_2|" $filepath
    
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: "Build release APK"
        run: ./gradlew assembleRelease --stacktrace

      - name: Decode keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > my-release-key.jks
  
      - name: Sign APK using apksigner
        env:
          KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          ${ANDROID_HOME}/build-tools/$(ls ${ANDROID_HOME}/build-tools | sort -V | tail -n 1)/apksigner sign \
            --ks my-release-key.jks \
            --ks-pass pass:"$KEYSTORE_PASSWORD" \
            --key-pass pass:"$KEY_PASSWORD" \
            --ks-key-alias "$KEY_ALIAS" \
            app/build/outputs/apk/release/app-release-unsigned.apk

      - name: "Rename APK"
        run: |
          ls app/build/outputs/apk/release
          VERSION_NAME="$(jq -r ".elements[0].versionName" "app/build/outputs/apk/release/output-metadata.json")"
          echo "Version name: $VERSION_NAME" >> "$GITHUB_STEP_SUMMARY"
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo '```json' >> "$GITHUB_STEP_SUMMARY"
          cat "app/build/outputs/apk/release/output-metadata.json" >> "$GITHUB_STEP_SUMMARY"
          echo >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"

      - name: Align APK
        run: zipalign -v -p 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/NewPipe_v${{ env.VERSION_NAME }}.apk
          
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.VERSION_NAME }}
          release_name: v${{ env.VERSION_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Upload APK to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/NewPipe_v${{ env.VERSION_NAME }}.apk
          asset_name: NewPipe_v${{ env.VERSION_NAME }}_perf.apk
          asset_content_type: application/vnd.android.package-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
